#ifndef _BOLT12_TYPES_
#define _BOLT12_TYPES_

enum eBolt12Types{
  TYPE_OFFER_CHAINS=		2,
  TYPE_OFFER_METADATA=		4,
  TYPE_OFFER_CURRENCY=		6,
  TYPE_OFFER_AMOUNT=		8,
  TYPE_OFFER_DESCRIPTION=	10,
  TYPE_OFFER_FEATURES=		12,
  TYPE_OFFER_ABSOLUTE_EXPIRY=	14,
  TYPE_OFFER_PATHS=		16,
  TYPE_OFFER_ISSUER=		18,
  TYPE_OFFER_QUANTITY_MAX=	20,
  TYPE_OFFER_ISSUER_ID=		22,
};

#endif
